[build]
  # Base directory del proyecto (donde está el package.json del frontend)
  base = "Frontend"

  # Comando para hacer el build
  command = "npm run build"

  # Directorio donde Vite genera los archivos estáticos
  publish = "dist"

[[redirects]]
  # Redirigir todas las rutas a index.html para el enrutamiento de React
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  # Versión de Node a usar
  NODE_VERSION = "18"
