name: keep-awake

on:
  schedule:
    - cron: "*/5 * * * *"   # cada 5 minutos
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping health endpoint
        run: |
          echo "🔁 Ping a https://colchonespremium2.onrender.com/api/health"
          curl -sS --max-time 20 --retry 2 --retry-delay 3 https://colchonespremium2.onrender.com/api/health -o /dev/null -w "HTTP %{http_code}\n" || true
